stages:
  - style
  - build
  - test
  - deploy

.notify: &notify
  - |
      if [ "$CI_JOB_STATUS" == "success" ]; then
        STATUS="УСПЕШНО"
      else
        STATUS="НЕУСПЕШНО"
      fi
      MESSAGE=$(cat <<-EOF
      Проект: $CI_PROJECT_NAME
      Автор коммита: $GITLAB_USER_NAME
      Этап: $CI_JOB_STAGE
      Статус: $STATUS
      Коммит: $CI_COMMIT_TITLE
      EOF
      )
      curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage \
      -d chat_id=${TELEGRAM_CHAT_ID} \
      -d text="$MESSAGE" \
      || echo "Failed to send Telegram notification"

style-job:
   stage: style
   tags:
     - style
   script:
     - cd src/cat/
     - clang-format -style=Google -Werror -n *.c *.h
     - cd ../grep/
     - clang-format -style=Google -Werror -n *.c *.h
   after_script:
     - *notify
   only:
     - develop
 
build-job:
   stage: build
   tags:
     - build
   script:
     - cd src/cat && make s21_cat 
     - cd ../grep && make s21_grep
   after_script:
     - *notify
   artifacts:
     paths:
       - src/cat/s21_cat
       - src/grep/s21_grep
     expire_in: 30 days
   only:
     - develop

test-job:
   stage: test
   tags:
     - test
   script:
     - (cd src/cat && make test) 2>/dev/null 1>cat_test.txt
     - (cd src/grep && make test) 2>/dev/null 1>grep_test.txt
     - |
       if ! grep -q "FAIL: 0" cat_test.txt || ! grep -q "FAIL: 0" grep_test.txt; then
         echo "Test failed."
         exit 1
       fi
   after_script:
     - *notify
   only:
     - develop

deploy-job:
   stage: deploy
   tags:
     - deploy
   when: manual
   script:
     - mkdir -p /home/gitlab-runner/.ssh
     - ssh-keyscan -H 192.10.10.2 >> /home/gitlab-runner/.ssh/known_hosts
     - chmod 777 src/run.sh
     - sh src/run.sh
   after_script:
     - *notify
   only:
     - develop
